repository_root: "{default.repository.root}/openjdk/{platform}/{architecture}"
version: 1.8.0_+ # becomes 1.8.0_25
memory_sizes:
  metaspace: 64m.. # permgen becomes metaspace
memory_heuristics:
  heap: 85
  metaspace: 10 # permgen becomes metaspace
  stack: 5
  native: 10